apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-pv-volume
spec:
  storageClassName: lab-pv
  capacity:
    storage: 1 Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab-pv-claim
spec:
  storageClassName: lab-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: lab-pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: lab-pv-claim
  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: http-server
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: storage
