apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: daemon
  name: daemon
spec:
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      labels:
        app: daemon
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: {}
status: {}
