apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  containers:
    - image: busybox
      name: writer
      volumeMounts:
        - mountPath: /messages
          name: cache-volume
      command: ["sh", "-c"]
      args:
        - echo hello > /messages/index.html
    - image: nginx
      name: reader
      volumeMounts:
        - mountPath: /usr/lib/nginx/html
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 500Mi
