http {
  include mime.types;

  server {
    listen 80;

    location / {
        alias /usr/share/nginx/html/cinema/;
        index  index.html index.htm;
        try_files $uri $uri/ /cinema/index.html;

        if ($uri = /cinema/index.html) {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            add_header Pragma "no-cache";
            add_header Expires "0";
        }
    }

    location /demo {
        alias /usr/share/nginx/html/demo/;
        index  index.html index.htm;
        try_files $uri $uri/ /demo/index.html;

        if ($uri = /demo/index.html) {
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            add_header Pragma "no-cache";
            add_header Expires "0";
        }
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
      root   /usr/share/nginx/html;
    }
  }
}

events {}